### PR TITLE
Spanish version of Alexa Chromecast Skill 2.0

### PR DESCRIPTION
**Pull request by CrStN224**
I have made an Spanish compatible version of this repository, I tested it and it works as a charm. I hope someone can tell me if they see any error, as I started coding this without any experience. Firstly I created it to my own purposes, but it would be great if someone more can enjoy it without having to make a rough translation.

### CODE REVIEW

**Comment by LukeChannings** [comment]
Hey @CrStN224,

Thank you so much for your work on this, making software more multilingual is important.

Unfortunately it's also complicated, which makes merging this request difficult. If I were to merge this request, the language would be in Spanish for everyone, which is probably not what you intended.

My suggestions are:

- Create a new readme file named `README.es.markdown`, and link from README.markdown like so: `[🇪🇸 Español](./README.es.markdown)
- Any files that are translated should be duplicated in an es folder, e.g. `config/es/interaction_model.json`, and the Spanish readme should include instructions specific for Spanish
- Changes to the shell scripts should be reverted, or the scripts should be restructured to use exported translation values. I'd prefer the former, because making multilingual shell scripts is difficult. I'd prefer not to just duplicate the shell scripts per language, because it means duplicating any changes.

Another option would be to have a Spanish branch, and update the readme to link to the Spanish branch instead of `README.es.markdown`.

**Comment by CrStN224** [comment]
That's right, I thought about creating a Spanish branch, this way it would be easier to compare or merge new changes on both branches, and wouldn't have to remove the changes made in the shell. Anyway, tell me what do you prefer. I will update the pull request and files to your conditions.

**Comment by LukeChannings** [comment]
The quickest and easiest solution would probably be to have a spanish branch, with a link to that in the README. You'll have to be responsible for keeping it up-to-date with master, though.

**Comment by CrStN224** [comment]
No problem, I will try my best. I'm receiving notifications to my phone whenever you make a change.

**Comment by LukeChannings** [comment]
Ok thanks, you'll need to:

- Update this MR to merge into a new spanish branch instead of master
- Create a new MR that updates README.markdown in master

**Comment by CrStN224** [comment]
Okay, could you please create the new branch? I have not managed to create it for myself, as I have searched for it but found nothing. I will update the MR and choose the new branch you created, and then push the MR updating the readme file with an url that redirects to the spanish branch for Spanish speakers.

**Comment by LukeChannings** [comment]
I've just pushed a spanish branch, hopefully you can update your MR now.

**Comment by LukeChannings** [comment]
I've just quickly added a link, no need for another PR.

Thanks for your contribution!

**Comment by CrStN224** [comment]
Great! You're welcome, thank you too!

**Pull request merged**
