### PR TITLE
Translation review

### PR DESCRIPTION
**Pull request by CrStN224**
Some translation adjustments

### CODE REVIEW

**Review by LukeChannings — APPROVED** [review]

**Comment by CrStN224** [comment]
Sure

**Comment by CrStN224** [comment]
Although I had to reedit the last commit to the master branch, could you push it?

**Comment by CrStN224** [comment]
Done.

**Comment by LukeChannings** [comment]
Merged. Thanks!

Git takes a bit of getting used to, you're doing fine! You should try to avoid force pushing, though.

**Comment by cristian44137** [comment]
> Merged. Thanks!
> 
> Git takes a bit of getting used to, you're doing fine! You should try to avoid force pushing, though.

Yeah, I think so too. I'm a newbie, but I'm also kind of perefectionist so I'm trying to not mess with the work you have done. Anyway, thank you, and happy holidays!

**Pull request merged**
